### ISSUE TITLE
Maven versioning issue

### ISSUE THREAD

**Issue by mepeisen** [DenizenScript/Denizen-Core#46]
While making changes to denizencore please always increment the version in pom.xml
In maven release version (such as 1.10) are meant to never change.
Changing release versions confuses maven repositories as they never try to update the release versions once they downloaded them.

**Comment by mcmonkey4eva** [comment]
No particular reason to ever rely on Denizen-Core. It's just a separation of some chunks used by Denizen (Bukkit).
