### ISSUE TITLE
bracked cmd timing

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-Core#61]
To clarify, let's say we have this example script for the old denizen:

```
    on click:
   - run chatEngine def:<script> path:loader
```
```
chatEngine:
  type: task
  loader:
  - foreach <li@1|2|3> {
    - narrate "2"
    }
```
To keep the same behavior as before in new Denizen, the example-script would need to be adjusted to:

```
chatEngine:
  type: task
  loader:
  - wait 0.5
  - foreach <li@1|2|3> {
    - narrate "2"
    }
```

These commits changed the behavior:
https://github.com/mcmonkey4eva/Denizen/commit/921e9a352ac9a080e8170318d2a0eef0e4b8c98b
https://github.com/DenizenScript/Denizen-Core/commit/5297ea172144afeacfdb2d8de35d067e88a74e78
...

Just want to ensure, you are aware of these effects, as the same scripts now run 0.5s faster.

**Comment by mcmonkey4eva** [comment]
> literally opening an issue post for a minor question that already had a straightforward answer on Discord

Could you not.
