### ISSUE TITLE
General feature requests

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-Core#62]
- [ ] webget headers option (using li@key/value|...)
- [ ] url_decode/encode tags
- [ ] base64_decode/encode tags
- [ ] load_text option in the yaml command so i don't have to do this every time:
```
- log <entry[res].result> type:clear file:<def[file]>
- yaml load:../../<def[file]> id:response
- adjust <def[npc]> skin_blob:<yaml[response].read[data.texture.value]>;<yaml[response].read[data.texture.signature]>
- yaml unload id:response
- adjust server delete_file:../../<def[file]>
```

EDIT: I'm dumb, webget already has a timeout

**Comment by mcmonkey4eva** [comment]
See https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1687 for header issue.
The rest: open as Denizen-Bukkit issues please.
