### ISSUE TITLE
Cancellable custom events, smart event matching, switches for "event" command, or an alternative

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-Core#66]
Currently, the event command is still using the old events system. It would be nice if the `event` command can have a facelift and implement many of these new features. Perhaps, say, new arguments such as:

```
- event [<event>|...] (cancellable:true/{false}) (context:<name>|<object>|...) (switches:<name>/<type>|...)
```

Where the event name can take arguments such as `<entity>` to mean entity, `<item>` for items, `<cuboid>` for cuboids, etc. The switch types can follow a similar suit, where the format would probably look something like `in/area|with/item|...` to mean `in:<area>` and `with:<item>`.

Perhaps an alternative is an "event" script container to allow users to define a custom script event. Then, the `event` command can also take scripts in the list of events to fire, and all of the ScriptEvent logic can be fired through the new script container.

**Comment by mcmonkey4eva** [comment]
A: No issues in the core repo please.
B: Being an experimental-status feature, plans regarding the event command are tracked off-GitHub.

**Comment by Morphan1** [comment]
A: Please disable the issue tracker if you don't want an issue tracker.
B: Define "off-GitHub" please, as that is where the code is.

If you could clearly state somewhere your rules for the issue trackers, that would be great. I don't believe there's ever been mention of this "no `experimental-status` plan talk" rule (which seems backwards for an open source project, but you can manage it how you see fit I guess), so knowing what other rules there might be would be nice to see before posting something.

**Comment by mcmonkey4eva** [comment]
A: I would if I could do so in a way that doesn't disable the ability to view past issues.
B: Places that aren't GitHub. (Discord, personal notes, random conversations, etc).
C: It's not a formal rule, just... that's being planned off-GitHub, and so it'd just make a mess to mix that and a GitHub issue, given that it's just ideas for building a new general system (as opposed to a straightforward bug or feature request).
