### ISSUE TITLE
improve map.include[]

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen-Core#70]
https://github.com/DenizenScript/Denizen-Core/blob/4e194449ddf254fc58b90806738962d3241b1746/src/main/java/com/denizenscript/denizencore/objects/core/MapTag.java#L295

Hi, is there a specific reason why a loop was used to put the entries instead of map#putAll?

This seems to make the code longer and might also affect performance negatively when causing
multiple resizes in the underlaying map, instead of a doing it in a single operation.

**Comment by mcmonkey4eva** [comment]
This is the type of question to ask on Discord @ https://discord.gg/Q6pZGSR not post in the core repo.
